### ISSUE TITLE
Integration with Quarto HTML Book

### ISSUE THREAD

**Issue by thealanjason** [ute/mathjax3eqno#1]
Thank you for this wonderful extension. 

I would be really happy if this works along with the quarto book project type. 

Could this be possible?

**Comment by ute** [comment]
Thank you for this suggestion, @thealanjason! 
I guess you mean that equations should be numbered by chapter, right?
It would be difficult to achieve that with mathjax only, since the numbering of chapters is done file by file by quarto. 
I am actually developing some of my extensions for writing course notes, as a book project, and it is quite hackish to get hold of the chapter numbers ([`custom-numbered-blocks`](https://github.com/ute/custom-numbered-blocks), [`qquestion`](https://github.com/ute/qquestion). This one is an exception, meant as a proof of concept for using mathjax built-in capabilities following a [suggestion](https://github.com/quarto-dev/quarto-cli/issues/4136) by @eeholmes.

I would love myself to be able to use the filter on book projects, especially, using equation tags. However, it means bypassing quarto's (and pandoc's ?) own cross-referencing algorithm and could result in a mess when mixing both. If you have an idea, or even a PR, this would be most welcome! 

Sorry for the late reply, I did not notice this issue.

Edit:

I think I can fix this one soon :-)

**Comment by ute** [comment]
Note to self, or to a helpful new contributor:
[setting section numbers in mathjax is possible](https://docs.mathjax.org/en/latest/input/tex/extensions/tagformat.html)
change mathjax3.js in assets folder accordingly, and include book processing stuff (like in qquestion)

**Comment by ute** [comment]
I have added a workaround for books, @thealanjason: a mathjax (LaTeX) function \setNewSection that needs to be invoked in the start of a new chapter. You can add this to the first equation in a chapter.

I close this issue now, but might add some automatism later to enable chapter numbering out of the box.

**Comment by ute** [comment]
I have added a workaround for books, @thealanjason: a mathjax (LaTeX) function `\setNewSection` that needs to be invoked in the start of a new chapter. You can add this to the first equation in a chapter.

I close this issue now, but might add some automatism later to enable chapter numbering out of the box.
